name: Metrics
on:
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics 1
        uses: lowlighter/metrics@v3.34
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics1.svg
          user: red40maxxer
          base: header, activity, repositories, metadata
          config_timezone: America/New_York
          config_twemoji: yes
          use_prebuilt_image: yes

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 600
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%

          plugin_lines: yes

          plugin_notable: yes
          plugin_notable_filter: stars:>30
          plugin_notable_from: organization
          plugin_notable_indepth: yes

      - name: Metrics 2
        uses: lowlighter/metrics@v3.34
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics2.svg
          user: red40maxxer
          base: ""
          config_timezone: America/New_York
          config_twemoji: yes  
          use_prebuilt_image: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
